--Exploring All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Exploring All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

--Exploring All Countries of Customers came from
SELECT DISTINCT country FROM gold.dim_customers;

--Exploring All Product Categories, Subcategories and Product Names
SELECT 
category, 
subcategory, 
product_name 
FROM gold.dim_products
ORDER BY 1,2,3

--Find The Date of First and Last Order & How Many Years of Sales are available
SELECT 
MIN(order_date) AS First_Order_Date, 
MAX(order_date) AS Last_Order_Date,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS Order_Range_Years
FROM gold.fact_sales;

--Find The Youngest and Oldest Birthdates & Age from Customer Table
SELECT 
MIN(birthdate) AS Oldest_Birthdate,
DATEDIFF(YEAR, MIN(birthdate),CURRENT_DATE) AS Oldest_Age,
MAX(birthdate) AS Youngest_Birthdate,
DATEDIFF(YEAR, MAX(birthdate),CURRENT_DATE) AS Youngest_Age
FROM gold.dim_customers

--Find The Total Sales
SELECT SUM(sales_amount) Total_sales FROM gold.fact_sales;

--Find How Many items are Sold
SELECT SUM(quantity) Total_Quantity FROM gold.fact_sales;

--Find The Average Selling Price
SELECT AVG(price) Avg_Price FROM gold.fact_sales;

--Find The Total Number of Orders
SELECT COUNT(DISTINCT order_number) Total_orders FROM gold.fact_sales;

--Find The Total Number of Products
SELECT COUNT(product_id) Total_Products FROM gold.dim_products;

--Total Number of Customers
SELECT COUNT(customer_id) Total_Customers FROM gold.dim_customers;

--Find The Total Number of Customers that has Placed an Order
SELECT 
COUNT(DISTINCT customer_id) Total_Customers 
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s 
ON c.customer_key=s.customer_key
WHERE S.order_number IS NOT NULL;

--Generate a Report That Shows all Key Metrics of The Business 
SELECT 'Total Sales' AS Measure_Name, SUM(sales_amount) AS Measure_Value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total No.Of orders',COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total No.Of Products' ,COUNT(product_id) FROM gold.dim_products
UNION ALL
SELECT 'Total No.Of Customers', COUNT(customer_id) FROM gold.dim_customers;

--Find The Total Customers by Country
SELECT 
country, 
COUNT(DISTINCT customer_id) 'Total Costomers' 
FROM gold.dim_customers
GROUP BY country 
ORDER BY 'Total Costomers' DESC

--Find Total Customers by Gender
SELECT 
gender, 
COUNT(DISTINCT customer_id) 'Total Costomers' 
FROM gold.dim_customers
GROUP BY gender 
ORDER BY 'Total Costomers' DESC

--Find The Total Products by category
SELECT 
category, 
COUNT(DISTINCT product_key) 'Total Products' 
FROM gold.dim_products
GROUP BY category 
ORDER BY 'Total Products' DESC

--Find The Average Cost in each Category
SELECT 
category, 
AVG(cost) 'Average Cost' 
FROM gold.dim_products
GROUP BY category 
ORDER BY 'Average Cost' DESC

--Find The Total Revenue Generated for each Category
SELECT 
p.category, 
SUM(sales_amount) 'Total Revenue' 
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p 
ON p.product_key= s.product_key
GROUP BY category 
ORDER BY 'Total Revenue' DESC

--Find The Total Revenue Generated by each Customer
SELECT 
c.customer_key,
c.first_name, 
c.last_name ,
SUM(sales_amount) 'Total Revenue' 
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c 
ON c.customer_key= s.customer_key
GROUP BY 
first_name,
last_name, 
c.customer_key  
ORDER BY 'Total Revenue' DESC

--Whats the Distribution of Sold items across countries
SELECT 
c.country,
SUM(quantity) 'Total Quantity' 
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c 
ON c.customer_key= s.customer_key
GROUP BY country  
ORDER BY 'Total Quantity' DESC

--Which 5 Products Generates the Highest Revenue
SELECT TOP 5 
P.product_name, 
SUM(f.sales_amount) 'Total Revunue' 
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON p.product_key=f.product_key
GROUP BY product_name 
ORDER BY 'Total Revunue' DESC

--What are the 5 Worst Performing Products in terms of Sales
SELECT TOP 5 
P.product_name, 
SUM(f.sales_amount) 'Total Revunue' 
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON p.product_key=f.product_key
GROUP BY product_name 
ORDER BY 'Total Revunue' ASC

-- By Using Window Functions Which 5 Products Generates the Highest Revenue
SELECT * 
FROM (
	SELECT p.product_name,
	SUM(Sales_amount) Total_sales,	
	RANK() OVER(ORDER BY SUM(sales_amount) DESC) AS rnk 
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p ON p.product_key=f.product_key 
	GROUP BY product_name)t
WHERE rnk <=5 

--Find The Top 10 Customers who have generated the Highest Revenue
SELECT TOP 10 
C.customer_id, 
c.first_name,
c.last_name, 
SUM(f.sales_amount) 'Total Revenue' 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
ON c.customer_key=f.customer_key
GROUP BY 
C.customer_id, 
c.first_name,
c.last_name
ORDER BY 'Total Revenue' DESC

--The 3 Customers with the fewest orders Placed
SELECT TOP 3 
C.customer_id, 
c.first_name,
c.last_name,
SUM(quantity) AS 'Total Orders' 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
ON c.customer_key=f.customer_key
GROUP BY 
C.customer_id, 
c.first_name,
c.last_name
ORDER BY 'Total Orders' ASC






